language: go
go_import_path: github.com/danielclasen/openclass

go:
- "1.11.x"

before_install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure

script:
- test -z "$(go fmt)"
- go vet ./...
- golint
- go test
- go doc